=== solenehuault/Challenge_3/first.dtd
<!ELEMENT cv (h1_cv*, etatcivil, phrasecle*, h1_formation, formation+, h1_xp, xp+, h1_competences, competences+, h1_loisirs, loisirs)>

	<!ELEMENT h1_cv (#CDATA)>
	<!ELEMENT etatcivil (nom, prenom, age, permis*, addresse, telephone, mail, photo*,)>
		<!ELEMENT nom (#PCDATA)>
		<!ELEMENT prenom (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT permis (#PCDATA)>

		<!ELEMENT adresse (n_rue, nomvoie, code_postal, ville)>
			<!ELEMENT n_rue (#PCDATA)>
			<!ELEMENT nomvoie (#PCDATA)>
			<!ELEMENT code_postal (#PCDATA)>
			<!ELEMENT ville (#PCDATA)>

		<!ELEMENT telephone(fixe*, portable*)>
			<!ELEMENT fixe (#PCDATA)>
			<!ELEMENT portable (#PCDATA)>

		<!ELEMENT mail (#PCDATA)>
		<!ELEMENT photo (EMPTY)>

	<!ELEMENT phrasecle (#CDATA)>

	<!ELEMENT h1_formation (#CDATA)>
	<!ELEMENT formation(titre, date, lieu, mention*)>
			<!ELEMENT titre (#PCDATA)>
			<!ELEMENT date (#PCDATA)>
			<!ELEMENT lieu (#PCDATA)>
			<!ELEMENT mention (#PCDATA)>

	<!ELEMENT h1_xp (#CDATA)>
	<!ELEMENT xp (titre, date, lieu, description)>
			<!ELEMENT titre (#PCDATA)>
			<!ELEMENT date (#PCDATA)>
			<!ELEMENT lieu (#PCDATA)>
			<!ELEMENT description (#PCDATA)>

	<!ELEMENT h1_competences (#CDATA)>
	<!ELEMENT competences (definition, niveau*)>
			<!ELEMENT definition (#PCDATA)>
			<!ELEMENT niveau (#PCDATA)>

	<!ELEMENT h1_loisirs (#CDATA)>
	<!ELEMENT loisirs (blabla+)>
			<!ELEMENT blabla (#PCDATA)>

=== solenehuault/Challenge_3/val.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "first.dtd">
<?xml-stylesheet type="text/css" href="styleval.css"?>
	<cv>
		<etatcivil>
				<nom>Susset</nom>
				<prenom>Valentin</prenom><br/>
				<age>27 ans</age>
				
			<adresse>
					<n_rue>52</n_rue>
					<nomvoie>rue Louis Pétri</nomvoie>
					<code_postal>35200</code_postal>
					<ville>Rennes</ville>
			</adresse>
			<telephone>
					<portable>07 83 81 45 27</portable>
			</telephone>
				<mail>valentinsusset@hotmail.com</mail>
		</etatcivil>
			<phrasecle>Développeur Web</phrasecle>
		<formation>
			<h1_formation>Formation</h1_formation>
			<titre>Licence LLCE anglais</titre>
			<date>2009-2012</date>
			<lieu>Bordeaux</lieu>
			<titre>Licence LLCE anglais</titre>
			<date>2009-2012</date>
			<lieu>Bordeaux</lieu>
			<titre>Licence LLCE anglais</titre>
			<date>2009-2012</date>
			<lieu>Bordeaux</lieu>
		</formation>	
		<xp>
			<h1_xp>Expérience Professionelle</h1_xp>
			<titre>Aide à domicile pour Alpha Care</titre>
			<date>2014/2015</date>
			<lieu>Liverpool, Angleterre</lieu>
			<description>Assistance avec les tâches domestiques, prise de médicaments, toilette, documentation stricte, etc.</description>
			<titre>Aide à domicile pour Alpha Care</titre>
			<date>2014/2015</date>
			<lieu>Liverpool, Angleterre</lieu>
			<description>Assistance avec les tâches domestiques, prise de médicaments, toilette, documentation stricte, etc.</description>
			<titre>Aide à domicile pour Alpha Care</titre>
			<date>2014/2015</date>
			<lieu>Liverpool, Angleterre</lieu>
			<description>Assistance avec les tâches domestiques, prise de médicaments, toilette, documentation stricte, etc.</description>
		</xp>
		<competences>
			<definition>Langages informatiques : html, css, javascript, ruby, php, mysql</definition>
			<definition>Langues : anglais courant</definition>
		</competences>
		<loisirs>
			<blabla>Centres d'intérêt : blablablabla</blabla>
		</loisirs>
	</cv>

=== solenehuault/Challenge_3/solene.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "first.dtd">
<?xml-stylesheet type="text/css" href="style_so.css"?>

	<cv>
		<etatcivil>
				<nom>Huault</nom>
				<prenom>Solène</prenom>
				<age>20 ans</age>
			<adresse>
					<n_rue>19</n_rue>
					<nomvoie>allée des Asturies</nomvoie>
					<code_postal>35200</code_postal>
					<ville>Rennes</ville>
			</adresse>
			<telephone>
					<portable>06 25 43 68 40</portable>
			</telephone>
				<mail>solene.huault@gmail.com</mail>
		</etatcivil>

		<h1_formation>Formation</h1_formation>
		<formation>
			<titre>Code Academy</titre>
			<date>De Mai 2016 à Janvier 2017</date>
			<lieu>Rennes</lieu>
			<mention>8 mois pour devenir dévellopeur web junior</mention>
		</formation>	
		
		<h1_xp>Expérience</h1_xp>
		<xp>
			<titre>Piscine 42</titre>
			<date>Septembre 2015</date>
			<lieu>Paris</lieu>
			<description>1 mois totalement dévoué à l'apprentisssage du langage C.</description>
		</xp>

		<h1_competences>Compétences</h1_competences>
		<competences>
			<definition>Langages informatique : HTML, CSS, XML, DTD, JS, PHP, SQL, C, Ruby, Bash, Python</definition>
		</competences>
		<competences>
			<definition>Langue vivantes : Anglais (courant), Allemand (niveau scolaire)</definition>
		</competences>

		<h1_loisirs>Loisirs</h1_loisirs>
		<loisirs>
			<blabla>Jeux vidéo: RPGs-solo</blabla>
			<blabla>Lecture : aventure-fantasy</blabla>
			<blabla>Danse : orientale et de salon</blabla>
			<blabla>Musique jouée: piano</blabla>
			<blabla>Théatre</blabla>
		</loisirs>
	</cv>

=== solenehuault/Challenge_3/juliette/juliette/xmlprojet_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "first.dtd">
<?xml-stylesheet type="text/css"  href="style.css" ?>
	<cv>
		<etatcivil>
				<nom>Saint-Jalme</nom>
				<prenom>Juliette</prenom>
				<age>23 ans</age>
				<permis></permis>
			<adresse>
					<n_rue>16</n_rue>
					<nomvoie>Cours Camille Claudel</nomvoie>
					<code_postal>35136</code_postal>
					<ville>Saint-Jacques de la lande</ville>
			</adresse>
			<telephone>
					<fixe></fixe>
					<portable>06 48 08 37 22</portable>
			</telephone>
				<mail>Juliette@Saint-Jalme.fr</mail>
			<photo></photo>
		</etatcivil>
			<phrasecle>phrase hyper philosophique qui epate....</phrasecle>
			<h1_formation>  </h1_formation>	
		<xp>
			<titre>xp: blablabla</titre>
			<date>blablabla</date>
			<lieu>blablabla</lieu>
			<description>blablabla</description>
		</xp>
				<xp>
			<titre>xp: blablabla</titre>
			<date>blablabla</date>
			<lieu>blablabla</lieu>
			<description>blablabla</description>
		</xp>
		<competences>
			<definition>Anglais</definition>
			<niveau>☺☺☺ • •</niveau>
		</competences>
		<competences>
			<definition>Espagnol</definition>
			<niveau>☺☺☺ • •</niveau>
		</competences>
		<competences>
			<definition>Italien</definition>
			<niveau>☺☺☺ • •</niveau>
		</competences>
		<loisirs>
			<blabla>J'aime le Tennis,le café,les Jeux videos,les Cartes magicset la navigation a voile</blabla>
		</loisirs>
	</cv>
