=== solenehuault/Challenge_3/solene/first.dtd
<!ELEMENT cv (etatcivil, phrasecle?, formation+, xp+, competences+, loisirs)>

	<!ELEMENT etatcivil (nom, prenom, age, nationalite, permis?, addresse, telephone, mail, photo?)>
		<!ELEMENT nom (#PCDATA)>
		<!ELEMENT prenom (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT nationalite (#PCDATA)>
		<!ELEMENT permis (#PCDATA)>
		<!ELEMENT adresse (n_rue, nomvoie, code_postal, ville)>
			<!ELEMENT n_rue (#PCDATA)>
			<!ELEMENT nomvoie (#PCDATA)>
			<!ELEMENT code_postal (#PCDATA)>
			<!ELEMENT ville (#PCDATA)>

		<!ELEMENT telephone(fixe?, portable)>
			<!ELEMENT fixe (#PCDATA)>
			<!ELEMENT portable (#PCDATA)>

		<!ELEMENT mail (#PCDATA)>
		<!ELEMENT photo (EMPTY)>

	<!ELEMENT phrasecle (#CDATA)>

	<!ELEMENT formation(titre, date, lieu, mention?)>
			<!ELEMENT titre (#PCDATA)>
			<!ELEMENT date (#PCDATA)>
			<!ELEMENT lieu (#PCDATA)>
			<!ELEMENT mention (#PCDATA)>

	<!ELEMENT xp (titre, date, lieu, description)>
			<!ELEMENT titre (#PCDATA)>
			<!ELEMENT date (#PCDATA)>
			<!ELEMENT lieu (#PCDATA)>
			<!ELEMENT description (#PCDATA)>

	<!ELEMENT competences (info, langue+, skill)>
			<!ELEMENT info (#PCDATA)>
			<!ELEMENT langue (#PCDATA)>
			<!ELEMENT skill (#PCDATA)>

	<!ELEMENT loisirs (jv, lecture, danse, musique, theatre)>
			<!ELEMENT jv (#PCDATA)>
			<!ELEMENT lecture (#PCDATA)>
			<!ELEMENT danse (#PCDATA)>
			<!ELEMENT musique (#PCDATA)>
			<!ELEMENT theatre (#PCDATA)>

=== solenehuault/Challenge_3/solene/solene.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "first.dtd">
<?xml-stylesheet type="text/xsl" href="my.xsl"?>
<cv>
	<etatcivil>
		<nom>Huault </nom>
		<prenom>Solène</prenom>
		<age>20 ans</age>
		<nationalite>Française</nationalite>
		<adresse>
			<n_rue>19</n_rue>
			<nomvoie>allée des Asturies</nomvoie>
			<code_postal>35200</code_postal>
			<ville>Rennes</ville>
		</adresse>
		<telephone>
			<portable>06 25 43 68 40</portable>
		</telephone>
		<mail>solene.huault@gmail.com</mail>
	</etatcivil>

	<formation>
		<titre>Code Académie</titre>
		<date>De mai 2016 à janvier 2017, </date>
		<lieu>Rennes</lieu>
		<mention>8 mois pour devenir développeur Web</mention>
	</formation>	

	<xp>
		<titre>Piscine 42</titre>
		<date>septembre 2015, </date>
		<lieu>Paris</lieu>
		<description>1 mois totalement dédié à l'apprentisssage du langage C</description>
	</xp>

	<competences>
		<info>HTML, CSS, XML, JS, PHP, SQL, C, Ruby, Bash, Python</info>
		<langue>Anglais : lu, écrit, parlé</langue>
		<langue>Allemand : notion</langue>
		<skill>Écoute, adaptabilité, résistance au stress, dynamisme, rigueur, créativité</skill>
	</competences>

	<loisirs>
		<jv>Jeux vidéo : RPGs</jv>
		<lecture>Lecture : aventure-fantasy</lecture>
		<danse>Danse : orientale et de salon</danse>
		<musique>Musique jouée : piano</musique>
		<theatre>Théatre</theatre>
	</loisirs>
</cv>
